yatube/posts/urls.py
from django.urls import path
from . import views

app_name = 'posts'

urlpatterns = [
    path('', views.index, name='index'),
    path('group/', views.groups_list, name='group_list'),
    path('group/<slug:slug>/', views.group_posts, name='group'),
]

yatube/yatube/urls.py
from django.contrib import admin
from django.urls import include, path

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('posts.urls', namespace='posts')),
    path('group/<slug:slug>/', include('posts.urls', namespace='posts'))
]

yatube/posts/models.py
from django.db import models
from django.contrib.auth import get_user_model

User = get_user_model()


class Group(models.Model):
    """ Модель для создания группы в соц.сети. """

    title = models.CharField(max_length=200)
    slug = models.SlugField(unique=True)
    # можно ли сделать так, чтобы была проверка
    # при создании поля на написания поля с большой
    # буквы (например, как метод capitalize в python для типа данных string?
    group_text = models.TextField()

    def __str__(self):
        return f'{self.title}'


class Post(models.Model):
    """ Модель для создания поста в соц.сети. """

    text = models.TextField()
    pub_date = models.DateTimeField(auto_now_add=True)
    author = models.ForeignKey(
        User,
        on_delete=models.CASCADE,
        related_name='posts'
    )
    group = models.ForeignKey(
        Group,
        blank=True,
        null=True,
        on_delete=models.CASCADE,
        related_name='posts',
    )


class Event(models.Model):
    """Модель для создания событий в соц. сети. """

    name = models.CharField(max_length=200)
    start_at = models.DateTimeField(auto_now_add=True)
    description = models.TextField()
    contact = models.EmailField()
    author = models.ForeignKey(
        User,
        on_delete=models.CASCADE,
        related_name='events'
    )
    location = models.CharField(max_length=400)

yatube/posts/views.py
from django.shortcuts import render, get_object_or_404

from .models import Group, Post


def index(request):
    """
    Вывести на экран главную страницу.

    :param request: HttpRequest
    :return: страница с шаблоном index.html
    """
    posts = Post.objects.order_by('-pub_date')[:10]

    templates = 'posts/index.html'

    context = {
        'posts': posts,
        'title': 'Главная страница',
    }
    return render(request, templates, context)


def groups_list(request):
    """
    Вывести на экран список созданных групп.

    :param request: HttpRequest
    :return: страница с шаблоном group_list.html
    """
    groups = Group.objects.order_by('title')[:10]

    templates = 'posts/group_list.html'

    context = {
        'groups': groups,
        'title': 'Группы'
    }
    return render(request, templates, context)


def group_posts(request, slug):
    """
    Вывести страницу с постами группы.

    :param request: HttpRequest
    :param slug: значение передается пользователем
    :return: страница с шаблоном index.html со списком постов группы
    """

    group = get_object_or_404(Group, slug=slug)

    templates = 'posts/index.html'

    posts = Post.objects.filter(group=group).order_by('-pub_date')[:10]
    context = {
        'group': group,
        'posts': posts,
        'title': group.title
    }
    return render(request, templates, context)

yatube/templates/base.html
<!DOCTYPE html>
{% load static %}
<html lang="ru"> <!-- Язык сайта - русский -->
  <head>
    <meta charset="utf-8"> <!-- Кодировка сайта -->
    <!-- Сайт готов работать с мобильными устройствами -->
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <!-- Загружаем фав-иконки -->
    <link rel="icon" href="{% static 'img/fav/favicon.ico' %}" type="image">
    <link rel="apple-touch-icon" sizes="180x180" href="{% static 'img/fav/apple-touch-icon.png' %}">
    <link rel="icon" type="image/png" sizes="32x32" href="{% static 'img/fav/favicon-16x16.png' %}">
    <link rel="icon" type="image/png" sizes="16x16" href="{% static 'img/fav/favicon-32x32.png' %}">
    <meta name="msapplication-TileColor" content="#000">
    <meta name="theme-color" content="#ffffff">
    <!-- Подключен файл со стандартными стилями бустрап -->
    <link rel="stylesheet" href="{% static 'css/bootstrap.min.css' %}">
    <title>{{ title }}</title>
  </head>
  <body>
    <header>
        {% include 'includes/header.html' %}
    </header>
    <main>
        {% block content %}
        {% endblock %}
    </main>
    <footer>
        {% include 'includes/footer.html' %}
    </footer>
  </body>
</html>

yatube/templates/includes/footer.html
<!DOCTYPE html>
<html lang="ru">
    <body>
        <footer class="border-top text-center py-3">
          <!-- тег span используется для добавления нужных стилей отдельным участкам текста -->
          <p>© 2021 Copyright <span style="color:red">Ya</span>tube</p>
        </footer>
    </body>
</html>

yatube/templates/includes/header.html
{% load static %}
<html lang="ru">
  <body>
      <header>
        <!-- Использованы классы бустрапа для создания типовой навигации с логотипом -->
        <!-- В дальнейшем тут будет создано полноценное меню -->
        <nav class="navbar navbar-light" style="background-color: lightskyblue">
          <div class="container">
            <a class="navbar-brand" href="{% url 'posts:index' %}">
              <img src="{% static 'img/logo.png' %}" width="30" height="30" class="d-inline-block align-top" alt="">
              <!-- тег span используется для добавления нужных стилей отдельным участкам текста -->
              <span style="color:red">Ya</span>tube</a>
            <a href="{% url 'posts:group_list' %}">
                <span style="color:black"><b>Группы</b></span>
            </a>
          </div>
        </nav>
      </header>
  </body>
</html>

yatube/templates/posts/group_list.html
{% extends 'base.html' %}
<head>
    <title>{{ title }}</title>
</head>
{% block content %}
  <div class="container py-5">
    <h1 style="text-align:center">{{ title }}</h1>
    <article>
    {% for group in groups %}
      <p>
          <a href="{% url 'posts:group' group.title %}">{{ group.title }}</a>
      </p>
      {{ group.group_text }}
      {% if not forloop.last %}<hr>{% endif %}
    {% endfor %}
    </article>
    <hr>
    <!-- под последним постом нет линии -->
  </div>
{% endblock %}

yatube/templates/posts/index.html
{% extends 'base.html' %}
{% block content %}
  <!-- класс py-5 создает отступы сверху и снизу блока -->
  <div class="container py-5">
    <h1 style="text-align:center">{{ title }}</h1>
    <article>
    {% for post in posts %}
      <ul>
        <li>
          Автор: {{ post.author.get_full_name }}
        </li>
        <li>
          Дата публикации: {{ post.pub_date }}
        </li>
      </ul>
      <p>
        {{ post.text }}
      </p>
      <p>
        {% if post.group %}
          <a href="{% url 'posts:group' post.group.title %}">все записи группы</a>
        {% endif %}
      </p>
      {% if not forloop.last %}<hr>{% endif %}
    {% endfor %}
    </article>
    <hr>
    <!-- под последним постом нет линии -->
  </div>
{% endblock %}